version: "3"

services: 
    db:
        image: postgres:latest
        #   restart: always
        tty: true
        volumes: 
            - pgdata:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=codeedu
        ports:
            - "5432:5432"
volumes:
    pgdata:
        external: true